################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################
# Include Pipeline Templates
include:
  - remote: 'https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/gitlab/php/defaults.yaml'

################################################################
# Defined Pipeline Stages
stages:
  - Php-7.4
  - Php-8.0
  - Php-8.1
  - Php-8.2
  - Php-8.3
  - Php-8.4
  - Builds

################################################################
# Quality Tests
################################################################

quality:php-8.4:
    extends:  .quality
    stage:    Php-8.4
    image:    registry.gitlab.com/badpixxel-projects/php-sdk:php-8.4

quality:php-8.3:
    extends:  .quality
    stage:    Php-8.3
    image:    registry.gitlab.com/badpixxel-projects/php-sdk:php-8.3

quality:php-8.2:
    extends:  .quality
    stage:    Php-8.2
    image:    registry.gitlab.com/badpixxel-projects/php-sdk:php-8.2

quality:php-8.1:
    extends:  .quality
    stage:    Php-8.1
    image:    registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1

quality:php-8.0:
    extends:  .quality
    stage:    Php-8.0
    image:    registry.gitlab.com/badpixxel-projects/php-sdk:php-8.0

quality:php-7.4:
    extends:  .quality
    stage:    Php-7.4
    image:    registry.gitlab.com/badpixxel-projects/php-sdk:php-7.4

################################################################
# Functional Tests
################################################################

functional:php-8.4:
    extends:  .functional
    stage:    Php-8.4
    image:    registry.gitlab.com/badpixxel-projects/php-sdk:php-8.4

functional:php-8.3:
    extends:  .functional
    stage:    Php-8.3
    image:    registry.gitlab.com/badpixxel-projects/php-sdk:php-8.3

functional:php-8.2:
    extends:  .functional
    stage:    Php-8.2
    image:    registry.gitlab.com/badpixxel-projects/php-sdk:php-8.2

functional:php-8.1:
    extends:  .functional
    stage:    Php-8.1
    image:    registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1

functional:php-8.0:
    extends:  .functional
    stage:    Php-8.0
    image:    registry.gitlab.com/badpixxel-projects/php-sdk:php-8.0

functional:php-7.4:
    extends:  .functional
    stage:    Php-7.4
    image:    registry.gitlab.com/badpixxel-projects/php-sdk:php-7.4

################################################################
# Build Documentation
################################################################
pages:
    image:      registry.gitlab.com/splashsync/php-console:pages
    stage:      Builds
    allow_failure: true
    tags:       ['Dedicated']
    services:
        - docker:dind
    ################################################################################
    # Run Test Script
    script:
        # Run Composer to Build deps
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/composer.sh  | bash
        # Build Documentation
        - php vendor/bin/grumphp run --tasks=build-docs
    artifacts:
        paths:
            - public
