################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################
# Include Pipeline Templates
include:
  - remote: 'https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/gitlab/php/defaults.yaml'

################################################################
# Quality Tests
################################################################

quality:php-8.2:
    extends: .quality
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.2

quality:php-8.1:
    extends: .quality
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1

quality:php-8.0:
    extends: .quality
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.0

quality:php-7.4:
    extends: .quality
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-7.4

################################################################
# Build Documentation
################################################################
pages:
    image:      registry.gitlab.com/splashsync/php-console:pages
    stage:      Builds
    tags:       ['Dedicated']
    services:
        - docker:dind
    ################################################################################
    # Run Test Script
    script:
        # Run Composer to Build deps
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/composer.sh  | bash
        # Build Documentation
        - php vendor/bin/grumphp run --tasks=build-docs
    artifacts:
        paths:
            - public
