# Travis CI Configuration File
language:   php

php:
    - 7.2
    - 7.3
    - 7.4
    
fast_finish: true    
    
cache:
  directories:
    - $HOME/.composer/cache
    
script:
    # Load Dependencies
    - composer update --no-suggest
    # Execute Grumphp >> Travis Minimal Tests Suite
    - php ./vendor/bin/grumphp run --testsuite=travis
    # Execute Grumphp >> CsFixer Tests Suite
    - if [[ ${TRAVIS_PHP_VERSION:0:3} > "7.0" ]]; then php ./vendor/bin/grumphp run --testsuite=csfixer; fi
    # With PHP > 7.0 => Execute Phpstan
    - if [[ ${TRAVIS_PHP_VERSION:0:3} > "7.0" ]]; then php ./vendor/bin/grumphp run --testsuite=phpstan; fi    
    # Execute Core Tests
    - php vendor/bin/phpunit
    # Show Outdated Packages
    - composer outdated -D

notifications:
  email:         
    on_success: never # default: change
    on_failure: never # default: always

