# Travis CI Configuration File
language:   php

php:
    - 5.6
    - 7.0
    - 7.1
    
cache:
  directories:
    - $HOME/.composer/cache
    
script:
    # With PHP 7 => Load Phpstan   
    - if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]]; then composer require phpstan/phpstan-shim --no-update; fi
    
    - composer update --no-suggest
    - php ./vendor/bin/grumphp run --testsuite=travis
    
    # With PHP 7 => Execute Phpstan 
    - if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]]; then php ./vendor/bin/grumphp run --testsuite=phpstan; fi    

    # Execute Core Tests   
    - phpunit

    # Show Outdated Packages   
    - composer outdated

        
notifications:
  email:         
    on_success: never # default: change
    on_failure: never # default: always

