# Travis CI Configuration File
language:   php

php:
    - 5.6
    - 7.0
    - 7.1
    
script:
    - composer update
    - php ./vendor/bin/grumphp run
        
notifications:
  email:         
    on_success: never # default: change
    on_failure: never # default: always

