# Travis CI Configuration File
language:   php

php:
    - 5.6
    - 7.0
    - 7.1
    
script:
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then composer remove phpstan/phpstan-shim -r; fi

    - composer update
    - php ./vendor/bin/grumphp run
        
notifications:
  email:         
    on_success: never # default: change
    on_failure: never # default: always

