
################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################################
# Docker Compose File
################################################################################

version: "3.5"

services:

    ################################################################################
    # PHP 8.2
    php-8.2:
        image:          registry.gitlab.com/badpixxel-projects/php-sdk:php-8.2
        container_name: php-core-8.2
        volumes:
            - ./:/var/www/html
            - vendor-php82:/var/www/html/vendor

    ################################################################################
    # PHP 8.1
    php-8.1:
        image:          registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1
        container_name: php-core-8.1
        volumes:
            - ./:/var/www/html
            - vendor-php81:/var/www/html/vendor

    ################################################################################
    # PHP 8.0
    php-8.0:
        image:          registry.gitlab.com/badpixxel-projects/php-sdk:php-8.0
        container_name: php-core-8.0
        volumes:
            - ./:/var/www/html
            - vendor-php80:/var/www/html/vendor

    ################################################################################
    # PHP 7.4
    php-7.4:
        image:      registry.gitlab.com/badpixxel-projects/php-sdk:php-7.4
        container_name: php-core-7.4
        volumes:
            - ./:/var/www/html
            - vendor-php74:/var/www/html/vendor

volumes:
    vendor-php82: ~
    vendor-php81: ~
    vendor-php80: ~
    vendor-php74: ~